// AUTO-GENERATED HEADERS aside, this is the only writer of
// `src/skill/bundled/index.generated.ts`.
//
// Build-time codegen for bundled skills. Reads
// `src/skill/bundled/<name>/SKILL.md` files, parses each frontmatter + body
// with the project's own `parseFrontmatter` (so user skill and bundled skill
// share a single parser), and emits a TS module containing the full
// `LoadedSkill[]` array with body inlined as JSON strings. Runtime path
// (loader.ts / registry.ts / bundled/index.ts) is unchanged from pre-Phase-16
// — bundled skills remain a static `LoadedSkill[]` array in memory.
//
// Generated file is checked into git. Re-run: `pnpm gen:skills`. Hooked into
// predev / pretypecheck / pretest / prebuild so it never falls out of sync
// with the SKILL.md sources.

import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { parseFrontmatter } from '../src/memory/auto-memory.js'

interface BuiltSkill {
  name: string
  description: string
  whenToUse?: string
  allowedTools?: string[]
  roles: string[]
  source: 'builtin'
  filePath: string
  body: string
}

async function main(): Promise<void> {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const repoRoot = path.resolve(here, '..')
  const bundledDir = path.join(repoRoot, 'src/skill/bundled')
  const outFile = path.join(bundledDir, 'index.generated.ts')

  const entries = await readdir(bundledDir, { withFileTypes: true })
  const dirs = entries
    .filter(entry => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name))

  const skills: BuiltSkill[] = []
  for (const entry of dirs) {
    const skillMdPath = path.join(bundledDir, entry.name, 'SKILL.md')
    let raw: string
    try {
      raw = await readFile(skillMdPath, 'utf8')
    } catch {
      throw new Error(
        `bundled skill directory "${entry.name}" missing SKILL.md (${skillMdPath})`,
      )
    }
    const { frontmatter, body } = parseFrontmatter(raw)

    const name = typeof frontmatter.name === 'string' ? frontmatter.name.trim() : ''
    if (!name) {
      throw new Error(
        `bundled SKILL.md ${skillMdPath} frontmatter missing required "name"`,
      )
    }
    if (name !== entry.name) {
      throw new Error(
        `bundled SKILL.md ${skillMdPath} frontmatter name="${name}" disagrees with directory name="${entry.name}"`,
      )
    }

    const description =
      typeof frontmatter.description === 'string' ? frontmatter.description.trim() : ''
    if (!description) {
      throw new Error(
        `bundled SKILL.md ${skillMdPath} frontmatter missing required "description"`,
      )
    }

    const whenToUse =
      typeof frontmatter.when_to_use === 'string' && frontmatter.when_to_use.trim().length > 0
        ? frontmatter.when_to_use.trim()
        : undefined

    const allowedToolsRaw = frontmatter['allowed-tools']
    const allowedTools = Array.isArray(allowedToolsRaw)
      ? allowedToolsRaw.map(value => String(value).trim()).filter(Boolean)
      : undefined

    const rolesRaw = frontmatter.roles
    const roles = Array.isArray(rolesRaw)
      ? rolesRaw.map(value => String(value).trim()).filter(Boolean)
      : []

    skills.push({
      name,
      description,
      whenToUse,
      allowedTools,
      roles,
      source: 'builtin',
      filePath: `builtin:${name}`,
      body: body.trim(),
    })
  }

  const header = [
    `// AUTO-GENERATED by scripts/build-bundled-skills.ts. DO NOT EDIT.`,
    `// Source of truth: src/skill/bundled/<name>/SKILL.md`,
    `// Re-run: pnpm gen:skills`,
    ``,
    `import type { LoadedSkill } from '../types.js'`,
    ``,
    `export const bundledSkills: LoadedSkill[] = ${JSON.stringify(skills, null, 2)}`,
    ``,
  ].join('\n')

  await writeFile(outFile, header, 'utf8')
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
